#!/usr/bin/env python

import sys, time, socket

HOST = 'localhost'    # The remote host
PORT = int(sys.argv[1]) # The same port as used by the server
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

# Define ourselves a function!
token = s.recv(1024)

#print "Defining a function called myFun"
#s.send(
#"Token: %s\n\
#Server-Command: define\n\
#Content-Type: text\n\
#Content-Length: 49\n\
#\n\
#function myFun() {return 'Hello World!' ;}" % token)
#fs = s.makefile()
#data = fs.readline()
#print "Token:", token
#print "Data: ", ' '.join(data.split(" ")[1:])

# Call that function!
fs = s.makefile()
print "Token: ", token
s.send(
"Token: %s\n\
Game-Command: greet\n\
Content-Type: text\n\
Content-Length: 0\n\
\n\
" % token)
time.sleep(1)

s.send(
"Token: %s\n\
Game-Command: uname\n\
Content-Type: text\n\
Content-Length: 0\n\
\n\
" % token)
time.sleep(1)

s.send(
"Token: %s\n\
Game-Command: chat\n\
Content-Type: text\n\
Content-Length: 23\n\
\n\
Hello guys, what's up?\n" % token)
time.sleep(1)


while True:
    data = fs.readline()
    print "Data: ", data

s.close()

time.sleep(2)

HOST = 'localhost'    # The remote host
PORT = int(sys.argv[1]) # The same port as used by the server
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
# Call that function!

print "Calling myFun"
s.send(
"Token: %s\n\
Server-Command: call\n\
Content-Type: text\n\
Content-Length: 6\n\
\n\
myFun" % token)
fs = s.makefile()
data = fs.readline()
print "Token:", token
print "Data: ", ' '.join(data.split(" ")[1:])

s.close()
